package views.data_panel.tabbedPane;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import models.GeneratedFileModel;
import models.ImportedData;
import utils.TreeModelBuilder;
import views.stlViewer.STLViewer;

public class GeneratedFilesPanel extends JPanel {

    /**
     * automatically generated by eclipse.
     */
    private static final long serialVersionUID = 4491905505931129624L;

    private JScrollPane jScrollPane;

    private JTextArea jTextArea;
    private STLViewer stlViewer;

    public GeneratedFilesPanel() {
        setBorder(BorderFactory.createTitledBorder("Generated Files"));
        setLayout(new BorderLayout());

        jScrollPane = new JScrollPane();
        add(jScrollPane, BorderLayout.CENTER);

        JPanel rightPanel = new JPanel();
        rightPanel.setPreferredSize(new Dimension(300, 200));
        rightPanel.setLayout(new BorderLayout());
        add(rightPanel, BorderLayout.EAST);


        jTextArea = new JTextArea("Select a file to view");
        jTextArea.setEditable(false);
        JScrollPane textScroll = new JScrollPane(jTextArea);
        textScroll.setBorder(BorderFactory.createTitledBorder("Details"));
        //textScroll.setPreferredSize(new Dimension(300, 250));
        rightPanel.add(textScroll, BorderLayout.CENTER);

        stlViewer = new STLViewer();
        rightPanel.add(stlViewer, BorderLayout.SOUTH);
    }

    public void updateGeneratedFilesView(ImportedData importedData) {
        JTree tree = new JTree(TreeModelBuilder.buildTreeModel(importedData));

        tree.addTreeSelectionListener((TreeSelectionEvent e) -> {

            DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                    tree.getLastSelectedPathComponent();

            if (!node.children().asIterator().hasNext()) {
                GeneratedFileModel fileModel = (GeneratedFileModel) node.getUserObject();
                jTextArea.setText(fileModel.getDetails());
                jTextArea.setCaretPosition(0);
                stlViewer.loadfile(fileModel.getFile());
            } else {
                jTextArea.setText("Select a file to view");
            }
        });

        jScrollPane.setViewportView(tree);
    }
}
