package views.data_panel.tabbedPane;

import controllers.DataPanelController;
import controllers.ImportDragAndDrop;
import controllers.ModelsPanelController;
import java.awt.dnd.DropTarget;
import javax.swing.JTabbedPane;
import models.ImportedData;

public class TabbedPane extends JTabbedPane {

    /**
     * Automatically generated by eclipse.
     */
    private static final long serialVersionUID = -2679305138083018523L;
    private DataImportPanel dataImportPanel;
    private DataSubjectListPanel dataSubjectListPanel;
    private GeneratedFilesPanel generatedFilesPanel;
    private ModelImportPanel modelImportPanel;

    private ImportDragAndDrop dragAndDropListener;

    public TabbedPane() {
        dataImportPanel = new DataImportPanel();
        add("Import", dataImportPanel);

        dataSubjectListPanel = new DataSubjectListPanel();
        add("Data", dataSubjectListPanel);

        generatedFilesPanel = new GeneratedFilesPanel();
        add("Generated Files", generatedFilesPanel);

        modelImportPanel = new ModelImportPanel();
        add("Manage 3D Models", modelImportPanel);

        enableDragAndDrop();
    }

    public void updateView(ImportedData data) {
        dataImportPanel.updateImportFileList(data);
        dataSubjectListPanel.updateView(data);
    }

    public void updateGenerateFilesView(ImportedData importedData) {
        generatedFilesPanel.updateGeneratedFilesView(importedData);
    }

    /**
     * Implement Drag and Drop operation.
     */
    private void enableDragAndDrop() {
        dragAndDropListener = new ImportDragAndDrop();
        new DropTarget(this, dragAndDropListener);
    }

    public void setDataPanelController(DataPanelController controller) {

        dataImportPanel.setController(controller);
        dataSubjectListPanel.setController(controller);
        dragAndDropListener.setController(controller);
    }

    public void setModelsPanelController(ModelsPanelController modelsPanelController) {
        modelImportPanel.setController(modelsPanelController);
    }

    public void toggleAllButtons(boolean isEnabled) {
        dataImportPanel.toggleButtons(isEnabled);
        dataSubjectListPanel.toggleButtons(isEnabled);
        modelImportPanel.toggleButtons(isEnabled);
        dragAndDropListener.setEnabled(isEnabled);
    }


    public ModelImportPanel getModelImportPanel() {
        return modelImportPanel;
    }

    public void setModelImportPanel(ModelImportPanel modelImportPanel) {
        this.modelImportPanel = modelImportPanel;
    }
}
