package views.models_panel;

import controllers.ModelsPanelController;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import models.ImportedData;
import models.ThreeDimensionalModels;

public class ModelsPanel extends JPanel {

    /**
     * Automatically generated by eclipse.
     */
    private static final long serialVersionUID = -205306541674299200L;
    private ThreeDModelsInfoPanel threeDModelsInfoPanel;
    private OptionsPanel optionsPanel;

    public ModelsPanel() {
        setLayout(new BorderLayout());
        setBorder(BorderFactory.createTitledBorder("Models"));

        threeDModelsInfoPanel = new ThreeDModelsInfoPanel();
        add(threeDModelsInfoPanel, BorderLayout.NORTH);

        optionsPanel = new OptionsPanel();
        add(optionsPanel, BorderLayout.CENTER);
    }

    public void setController(ModelsPanelController controller) {
        optionsPanel.setController(controller);
    }

    public void updateViews(ThreeDimensionalModels models, ImportedData importedData) {
        threeDModelsInfoPanel.updateModelInfo(models);
        optionsPanel.updateModelList(models, importedData);
    }

    public void toggleButtons(boolean isEnabled) {
        optionsPanel.toggleButtons(isEnabled);
    }
}
