package views.models_panel;

import controllers.ModelsPanelController;
import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import models.FileModel;
import models.ImportedData;
import models.ThreeDimensionalModels;
import org.apache.commons.io.FilenameUtils;

public class ModelsOptionPanel extends JPanel {

    /**
     * Automatically generated by eclipse.
     */
    private static final long serialVersionUID = -2454635272069727627L;

    private ModelsPanelController controller;

    private List<JCheckBox> checkBoxList;
    private JPanel checkboxPanel;
    private JScrollPane jScrollPane;
    private ButtonPanel buttonPanel;

    public ModelsOptionPanel() {
        setBorder(BorderFactory.createTitledBorder("3D Models"));
        setLayout(new BorderLayout());

        checkBoxList = new ArrayList<>();

        checkboxPanel = new JPanel();
        checkboxPanel.setLayout(new BoxLayout(checkboxPanel, BoxLayout.Y_AXIS));

        jScrollPane = new JScrollPane(checkboxPanel);
        add(jScrollPane, BorderLayout.CENTER);

        buttonPanel = new ButtonPanel();
        add(buttonPanel, BorderLayout.SOUTH);
    }

    public void setController(ModelsPanelController controller) {
        this.controller = controller;
        buttonPanel.setController(this.controller);
    }

    public void updateModelList(ThreeDimensionalModels models, ImportedData importedData) {
        checkBoxList.clear();
        checkboxPanel.removeAll();
        models.getModels().forEach(model -> addCheckBox(model));

        buttonPanel.updateButtonStates(models, importedData);
        repaint();
        revalidate();
    }

    private void addCheckBox(FileModel model) {
        JCheckBox checkBox = new JCheckBox(FilenameUtils.removeExtension(model.getFileName()) + isBuiltInText(model));
        checkBox.setSelected(model.isSelected());
        checkBox.addItemListener((ItemEvent e) -> {
            int indexOfChangedItem = checkBoxList.indexOf(e.getItem());
            controller.updateSelection(indexOfChangedItem, e.getStateChange());
        });

        checkboxPanel.add(checkBox);
        checkBoxList.add(checkBox);
    }

    private String isBuiltInText(FileModel model) {
        return model.isDeletable() ? "" : " (built-in)";
    }

    public void toggleButtons(boolean isEnabled) {
        checkBoxList.forEach(checkbox -> checkbox.setEnabled(isEnabled));
        buttonPanel.toggleButtons(isEnabled);
    }
}
