package views.models_panel;

import controllers.ModelsPanelController;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import models.ImportedData;
import models.ThreeDModels;

public class ModelsPanel extends JPanel {

    /**
     * Automatically generated by eclipse.
     */
    private static final long serialVersionUID = -205306541674299200L;
    private ModelsInfoPanel modelsInfoPanel;
    private ModelsOptionPanel modelsOptionPanel;

    public ModelsPanel() {
        setLayout(new BorderLayout());
        setBorder(BorderFactory.createTitledBorder("Models"));

        modelsInfoPanel = new ModelsInfoPanel();
        add(modelsInfoPanel, BorderLayout.NORTH);

        modelsOptionPanel = new ModelsOptionPanel();
        add(modelsOptionPanel, BorderLayout.CENTER);
    }

    public void setModelsPanelController(ModelsPanelController controller) {
        modelsOptionPanel.setController(controller);
    }

    public void updateViews(ThreeDModels models, ImportedData importedData) {
        modelsInfoPanel.updateModelInfo(models);
        modelsOptionPanel.updateModelList(models, importedData);
    }

    public void toggleButtons(boolean isEnabled) {
        modelsOptionPanel.toggleButtons(isEnabled);
    }
}
