package views.data_panel;

import controllers.DataPanelController;
import controllers.ModelsPanelController;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import models.ImportedData;
import views.data_panel.tabbedPane.TabbedPane;

public class DataPanel extends JPanel {

    /**
     * automatically generated by eclipse.
     */
    private static final long serialVersionUID = 4732367937089784954L;
    private DataInfoPanel dataInfoPanel;
    private TabbedPane tabbedPane;

    public DataPanel() {
        setBorder(BorderFactory.createEmptyBorder());
        setLayout(new BorderLayout());

        dataInfoPanel = new DataInfoPanel();
        add(dataInfoPanel, BorderLayout.NORTH);

        tabbedPane = new TabbedPane();
        add(tabbedPane, BorderLayout.CENTER);
    }

    public void updateDataViews(ImportedData data) {
        dataInfoPanel.updateView(data);

        tabbedPane.updateView(data);
        tabbedPane.setSelectedIndex(1);
    }

    public void updateGenerateFilesView(ImportedData importedData) {
        tabbedPane.updateGenerateFilesView(importedData);
        tabbedPane.setSelectedIndex(2);
    }

    public void setDataPanelController(DataPanelController controller) {
        tabbedPane.setDataPanelController(controller);
    }

    public void setModelsPanelController(ModelsPanelController modelsPanelController) {
        tabbedPane.setModelsPanelController(modelsPanelController);
    }

    public void toggleAllButtons(boolean isEnabled) {
        tabbedPane.toggleAllButtons(isEnabled);
    }


    public TabbedPane getTabbedPane() {
        return tabbedPane;
    }

    public void setTabbedPane(TabbedPane tabbedPane) {
        this.tabbedPane = tabbedPane;
    }
}
